{pkgs, ...}:
{
  # List packages installed in system profile. To search, run:
  # $ nix search wget
  environment.systemPackages = with pkgs; [
    adoptopenjdk-bin
    ant
    bats
    borgbackup
    chromium
    curl
    dropbox-cli
    git
    gnome_mplayer
    gnupg
    gradle
    graphviz
    groovy
    htop
    inkscape
    irssi
    jbake
    jetbrains.idea-community
    libdvdcss
    libdvdnav
    libdvdread
    libnotify
    libreoffice
    lsof
    lynx
    mkpasswd
    mplayer
    multimc
    mysqlWorkbench
    netbeans
    networkmanagerapplet
    nixops
    nox
    obs-studio
    pidgin
    psmisc
    pwgen
    python
    python3
    python35Packages.youtube-dl
    python36Packages.xdot
    rxvt_unicode-with-plugins
    screen
    skypeforlinux
    tdesktop
    tmux
    travis
    tree
    unzip
    utillinux
    vim
    virtualbox
    visualvm
    vlc
    wget
    xarchiver
    xbindkeys
    xfontsel
    xorg.appres
    xorg.xclock
    xorg.xev
    xorg.xmodmap
    xterm
    zip
  ];
}
