-- This file has been generated by /nix/store/lk898b5ckngis6ij9jrbbd9jla1jsf1b-notion/bin/notion. Do not edit.
return {
    ["date"] = {
        ["date_format"] = "%a %Y-%m-%d %H:%M",
    },
    ["load"] = {
    },
    ["mail"] = {
    },
}

