-- This file has been generated by /nix/store/lk898b5ckngis6ij9jrbbd9jla1jsf1b-notion/bin/notion. Do not edit.
return {
    [0] = {
        ["managed"] = {
            [1] = {
                ["managed"] = {
                    [1] = {
                        ["level"] = 0,
                        ["split_tree"] = {
                            ["brs"] = 26,
                            ["tl"] = {
                                ["brs"] = 1117,
                                ["tl"] = {
                                    ["brs"] = 527,
                                    ["tl"] = {
                                        ["regparams"] = {
                                            ["managed"] = {
                                            },
                                            ["name"] = "WFrame",
                                            ["mode"] = 1,
                                            ["type"] = "WFrame",
                                        },
                                        ["type"] = "WSplitRegion",
                                    },
                                    ["br"] = {
                                        ["regparams"] = {
                                            ["managed"] = {
                                            },
                                            ["name"] = "Tiling Frame",
                                            ["mode"] = 1,
                                            ["type"] = "WFrame",
                                        },
                                        ["type"] = "WSplitRegion",
                                    },
                                    ["dir"] = "vertical",
                                    ["tls"] = 527,
                                    ["type"] = "WSplitSplit",
                                },
                                ["br"] = {
                                    ["regparams"] = {
                                        ["managed"] = {
                                            [1] = {
                                                ["managed"] = {
                                                    [1] = {
                                                        ["bottom"] = true,
                                                        ["geom"] = {
                                                            ["x"] = 0,
                                                            ["w"] = 1114,
                                                            ["h"] = 1030,
                                                            ["y"] = 1,
                                                        },
                                                        ["checkcode"] = 1,
                                                        ["windowid"] = 20971533,
                                                        ["sizepolicy"] = "full",
                                                        ["level"] = 1,
                                                        ["type"] = "WClientWin",
                                                    },
                                                },
                                                ["geom"] = {
                                                    ["x"] = 1,
                                                    ["w"] = 1115,
                                                    ["h"] = 1032,
                                                    ["y"] = 21,
                                                },
                                                ["level"] = 0,
                                                ["sizepolicy"] = "full",
                                                ["name"] = "WGroupCW",
                                                ["switchto"] = true,
                                                ["type"] = "WGroupCW",
                                            },
                                        },
                                        ["name"] = "WFrame<1>",
                                        ["mode"] = 1,
                                        ["type"] = "WFrame",
                                    },
                                    ["type"] = "WSplitRegion",
                                },
                                ["dir"] = "horizontal",
                                ["tls"] = 803,
                                ["type"] = "WSplitSplit",
                            },
                            ["br"] = {
                                ["type"] = "WSplitST",
                            },
                            ["dir"] = "vertical",
                            ["tls"] = 1054,
                            ["type"] = "WSplitSplit",
                        },
                        ["geom"] = {
                            ["x"] = 0,
                            ["w"] = 1920,
                            ["h"] = 1080,
                            ["y"] = 0,
                        },
                        ["bottom"] = true,
                        ["name"] = "WTiling",
                        ["sizepolicy"] = "full",
                        ["type"] = "WTiling",
                    },
                },
                ["geom"] = {
                    ["x"] = 0,
                    ["w"] = 1920,
                    ["h"] = 1080,
                    ["y"] = 0,
                },
                ["initial_outputs"] = {
                    [1] = "LVDS1",
                },
                ["level"] = 0,
                ["sizepolicy"] = "full",
                ["name"] = "WGroupWS",
                ["switchto"] = true,
                ["type"] = "WGroupWS",
            },
            [2] = {
                ["managed"] = {
                    [1] = {
                        ["level"] = 0,
                        ["split_tree"] = {
                            ["brs"] = 26,
                            ["tl"] = {
                                ["regparams"] = {
                                    ["managed"] = {
                                        [1] = {
                                            ["managed"] = {
                                                [1] = {
                                                    ["bottom"] = true,
                                                    ["geom"] = {
                                                        ["x"] = 2,
                                                        ["w"] = 1914,
                                                        ["h"] = 1030,
                                                        ["y"] = 1,
                                                    },
                                                    ["checkcode"] = 2,
                                                    ["windowid"] = 35651597,
                                                    ["sizepolicy"] = "full",
                                                    ["level"] = 1,
                                                    ["type"] = "WClientWin",
                                                },
                                            },
                                            ["geom"] = {
                                                ["x"] = 1,
                                                ["w"] = 1918,
                                                ["h"] = 1032,
                                                ["y"] = 21,
                                            },
                                            ["level"] = 0,
                                            ["sizepolicy"] = "full",
                                            ["name"] = "WGroupCW<4>",
                                            ["switchto"] = true,
                                            ["type"] = "WGroupCW",
                                        },
                                    },
                                    ["name"] = "WFrame<3>",
                                    ["mode"] = 1,
                                    ["type"] = "WFrame",
                                },
                                ["type"] = "WSplitRegion",
                            },
                            ["br"] = {
                                ["type"] = "WSplitST",
                            },
                            ["dir"] = "vertical",
                            ["tls"] = 1054,
                            ["type"] = "WSplitSplit",
                        },
                        ["geom"] = {
                            ["x"] = 0,
                            ["w"] = 1920,
                            ["h"] = 1080,
                            ["y"] = 0,
                        },
                        ["bottom"] = true,
                        ["name"] = "WTiling<1>",
                        ["sizepolicy"] = "full",
                        ["type"] = "WTiling",
                    },
                },
                ["hidden"] = true,
                ["initial_outputs"] = {
                    [1] = "LVDS1",
                },
                ["geom"] = {
                    ["x"] = 0,
                    ["w"] = 1920,
                    ["h"] = 1080,
                    ["y"] = 0,
                },
                ["level"] = 0,
                ["name"] = "WGroupWS<1>",
                ["sizepolicy"] = "full",
                ["type"] = "WGroupWS",
            },
            [3] = {
                ["managed"] = {
                    [1] = {
                        ["managed"] = {
                        },
                        ["mode"] = 0,
                        ["geom"] = {
                            ["x"] = 640,
                            ["w"] = 640,
                            ["h"] = 480,
                            ["y"] = 300,
                        },
                        ["level"] = 1025,
                        ["bottom"] = true,
                        ["name"] = "*scratchpad*",
                        ["sizepolicy"] = "free_glue",
                        ["type"] = "WFrame",
                    },
                },
                ["geom"] = {
                    ["x"] = 0,
                    ["w"] = 1920,
                    ["h"] = 1080,
                    ["y"] = 0,
                },
                ["name"] = "*scratchws*",
                ["pseudomodal"] = true,
                ["level"] = 1,
                ["unnumbered"] = true,
                ["hidden"] = true,
                ["sizepolicy"] = "full",
                ["initial_outputs"] = {
                },
                ["type"] = "WGroupWS",
            },
        },
        ["name"] = "WScreen",
        ["type"] = "WScreen",
    },
}

