-- This file has been generated by /nix/store/lk898b5ckngis6ij9jrbbd9jla1jsf1b-notion/bin/notion. Do not edit.
return {
    [1] = "menu.mainmenu:session/exit",
    [2] = "run:idea-community",
    [3] = "workspacelayout:",
    [4] = "workspacename:",
    [5] = "run:chromium",
    [6] = "run:chrom",
    [7] = "menu.mainmenu:session/restart",
    [8] = "run:chomium",
}

